# Generated by Django 5.2 on 2025-04-18 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_id', models.PositiveIntegerField(null=True)),
                ('dtstamp', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime)),
                ('w_name', models.CharField(blank=True, max_length=20, null=True)),
                ('w_email', models.CharField(blank=True, max_length=20, null=True)),
                ('w_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('w_remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('test', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
