# Generated by Django 5.2 on 2025-04-13 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_id', models.PositiveIntegerField(null=True)),
                ('dtstamp', models.DateTimeField(verbose_name=datetime.datetime)),
                ('v_regnNo', models.CharField(max_length=20)),
                ('v_model', models.CharField(max_length=20)),
                ('v_make', models.CharField(max_length=20)),
                ('v_remarks', models.CharField(max_length=20)),
            ],
        ),
    ]
