# Generated by Django 5.2 on 2025-04-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='test',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
