# Generated by Django 5.2 on 2025-04-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleApi', '0002_vehicle_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='v_make',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_regnNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_remarks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
